### ISSUE TITLE
Error in searching mass shifts

### ISSUE THREAD

**Issue by k-p4** [marjanfaizi/MSModDetector#2]
Hi, I was interested in testing out MSModDetector with some files I have. However I am running into this issue. 
```
---------------------------------------------------------------

Load files...

Detecting mass shifts...
[==================================================] 100.0% ...

Searching for PTM combinations:
Traceback (most recent call last):
  File "\MSModDetector\src\main.py", line 158, in <module>
[P68431.fasta.txt](https://github.com/marjanfaizi/MSModDetector/files/12501373/P68431.fasta.txt)

[modifications_P68431.csv](https://github.com/marjanfaizi/MSModDetector/files/12501366/modifications_P68431.csv)

    mass_shifts.add_ptm_patterns_to_table()
  File "\MSModDetector\src\mass_shifts.py", line 211, in add_ptm_patterns_to_table
    self.identified_masses_df = pd.merge(best_ptm_patterns[["mass shift", "PTM pattern"]],
  File "\miniconda3\lib\site-packages\pandas\core\reshape\merge.py", line 148, in merge
    op = _MergeOperation(
  File "\miniconda3\lib\site-packages\pandas\core\reshape\merge.py", line 741, in __init__
    self._maybe_coerce_merge_keys()
  File "\miniconda3\lib\site-packages\pandas\core\reshape\merge.py", line 1401, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat
```

**Comment by marjanfaizi** [comment]
Hi @k-p4, thanks for your interest! MSModDetector was tested on Python 3.8.5 and is using pandas 1.1.3. Are you getting this error using the same versions?

**Comment by k-p4** [comment]
Hi, yes. I installed the dependencies as in the requirements.txt files into a new venv.

**Comment by marjanfaizi** [comment]
Oh I see, is it possible to attach your modification and fasta files to this issue and can you maybe also type “conda list” in your activated environment or “pip list” and send a list of the package versions? I’d like to try to reproduce the error. Thanks!
